n = input('Digite algo: ')

print(type(n))
print('É alfa? ',n.isalpha())
print('É ALFANUMERICO? ',n.isalnum())
print(n.isascii())
print('É DECIMAL? ',n.isdecimal())
print('É UM DIGITO? ',n.isdigit())
print('ESTÁ EM MINUSCULAS? ',n.islower())
print('É NUMERICO? ',n.isnumeric())